import {colorAt} from './replay.mjs';
const COLORS=['#8ad2df','#d6c094','#718fe0','#78b6aa'];
export {COLORS};
function range(state){const end=Math.max(0,Math.min(state.clip.t.length-1,Math.floor(state.index)));const size=Math.min(state.windowSize||200,state.clip.t.length);const start=Math.max(0,end-size+1);return {end,start,size,offset:state.clip.sampleOffset||0,span:Math.max(1,size-1)}}
function inside(ctx,r,paint){ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.w,r.h);ctx.clip();ctx.translate(r.x,r.y);ctx.textAlign='left';ctx.textBaseline='alphabetic';paint(r.w,r.h);ctx.restore()}
function axes(ctx,w,h,max,state,variation=false){const p={x:48,y:18,w:Math.max(1,w-67),h:Math.max(1,h-53)},v=range(state);ctx.lineWidth=.7;ctx.font='11px ui-monospace, monospace';ctx.fillStyle='#6c8899';ctx.strokeStyle='#20323e';for(let j=0;j<=4;j++){const y=p.y+j*p.h/4;ctx.beginPath();ctx.moveTo(p.x,y);ctx.lineTo(p.x+p.w,y);ctx.stroke();ctx.fillText((max*(1-j/4)).toFixed(max<3?2:0),6,y+4)}for(let j=0;j<=4;j++){const x=p.x+p.w*j/4;ctx.fillText(String(Math.round(v.offset+v.start+j*v.span/4)),x-6,h-18)}ctx.fillText(variation?'σ · a.u.':'|H| · a.u.',8,11);ctx.textAlign='right';ctx.fillText('Sample index',w-20,h-3);ctx.textAlign='left';return {p,v}}
function traces(ctx,w,h,state,variation){const c=state.clip,max=variation?c.vmax*1.12:Math.max(.001,c.max*1.03),{p,v}=axes(ctx,w,h,max,state,variation);const indices=state.indices||c.indices;ctx.save();ctx.beginPath();ctx.rect(p.x,p.y,p.w,p.h);ctx.clip();for(let k=0;k<(variation?1:indices.length);k++){ctx.strokeStyle=variation?'#9fd6c4':COLORS[k%4];ctx.lineWidth=1.25;ctx.beginPath();let active=false;for(let i=v.start;i<=v.end;i++){const val=variation?c.variation[i]:c.amplitudes[i][indices[k]];if(val==null){active=false;continue}const x=p.x+(i-v.start)/v.span*p.w,y=p.y+p.h*(1-val/max);if(active)ctx.lineTo(x,y);else ctx.moveTo(x,y);active=true}ctx.stroke()}ctx.restore()}
function heat(ctx,w,h,state){const c=state.clip,v=range(state),bins=c.binIds.length,p={x:48,y:14,w:Math.max(1,w-115),h:Math.max(1,h-45)};ctx.fillStyle='#081222';ctx.fillRect(p.x,p.y,p.w,p.h);for(let i=v.start;i<=v.end;i++){const x=p.x+(i-v.start)/v.size*p.w;for(let k=0;k<bins;k++){ctx.fillStyle=colorAt(c.amplitudes[i][k],c.lo,c.hi);ctx.fillRect(x,p.y+(bins-1-k)*p.h/bins,p.w/v.size+.2,p.h/bins+.2)}}ctx.fillStyle='#7896a7';ctx.font='11px ui-monospace, monospace';for(let j=0;j<=4;j++){const k=Math.round((bins-1)*(1-j/4));ctx.fillText(c.binIds[k],12,p.y+p.h*j/4+3);ctx.fillText(Math.round(v.offset+v.start+v.span*j/4),p.x+p.w*j/4-5,h-14)}ctx.fillText('Bin',10,10);ctx.textAlign='center';ctx.fillText('Sample index',w/2,h-1);ctx.textAlign='left';for(let y=0;y<p.h;y++){ctx.fillStyle=colorAt(c.hi-(c.hi-c.lo)*y/p.h,c.lo,c.hi);ctx.fillRect(w-40,p.y+y,7,1)}ctx.fillStyle='#7896a7';ctx.fillText(c.hi.toFixed(1),w-30,p.y+9);ctx.fillText(c.lo.toFixed(1),w-30,p.y+p.h);ctx.fillText('a.u.',w-50,h-2)}
function surface(ctx,w,h,state){const c=state.clip,v=range(state),count=c.binIds.length,a=(state.angle??-35)*Math.PI/180,s=Math.min(w/3.25,h/2.7);const project=(x,y,z)=>{const u=x*Math.cos(a)-y*Math.sin(a),d=x*Math.sin(a)+y*Math.cos(a);return [w/2+u*s,h*.58+d*.43*s-z*s*.9,d]};const line=(p,q)=>{const x=project(...p),y=project(...q);ctx.beginPath();ctx.moveTo(x[0],x[1]);ctx.lineTo(y[0],y[1]);ctx.stroke()};ctx.strokeStyle='#2b4352';ctx.lineWidth=.65;for(let j=0;j<=8;j++){line([-1,-.8+j*.2,0],[1,-.8+j*.2,0]);line([-1+j*.25,-.8,0],[-1+j*.25,.8,0])}line([-1,-.8,0],[-1,-.8,1.13]);const sampled=[],step=Math.max(1,Math.ceil((v.end-v.start)/110));for(let i=v.start;i<=v.end;i+=step)sampled.push(i);if(sampled.at(-1)!==v.end)sampled.push(v.end);const point=(i,k)=>project(-1+2*k/(count-1),.8-1.6*(i-v.start)/v.span,Math.max(0,Math.min(1,(c.amplitudes[i][k]-c.lo)/(c.hi-c.lo))));if(state.view==='points'){const dots=[];for(const i of sampled)for(let k=0;k<count;k++)dots.push({p:point(i,k),color:colorAt(c.amplitudes[i][k],c.lo,c.hi,.9)});dots.sort((a,b)=>a.p[2]-b.p[2]);for(const d of dots){ctx.fillStyle=d.color;ctx.fillRect(d.p[0],d.p[1],2,2)}}else{const faces=[];for(let j=1;j<sampled.length;j++){const i=sampled[j-1],n=sampled[j];for(let k=0;k<count-1;k++){const p=[point(i,k),point(i,k+1),point(n,k+1),point(n,k)];faces.push({p,d:p.reduce((sum,a)=>sum+a[2],0),value:(c.amplitudes[i][k]+c.amplitudes[n][k]+c.amplitudes[i][k+1]+c.amplitudes[n][k+1])/4})}}faces.sort((a,b)=>a.d-b.d);for(const f of faces){ctx.beginPath();ctx.moveTo(f.p[0][0],f.p[0][1]);for(const p of f.p.slice(1))ctx.lineTo(p[0],p[1]);ctx.closePath();ctx.fillStyle=colorAt(f.value,c.lo,c.hi,.95);ctx.fill();ctx.strokeStyle='#b2deeb12';ctx.lineWidth=.35;ctx.stroke()}}ctx.font='11px ui-monospace, monospace';ctx.fillStyle='#86a6b8';ctx.fillText('CSI bin',w*.38,h*.86);ctx.textAlign='right';ctx.fillText('Sample index',w-18,h*.71);ctx.textAlign='left';ctx.fillText('|H| · a.u.',18,h*.28);ctx.font='10px ui-monospace, monospace';ctx.fillStyle='#658493';ctx.fillText('Height scale: P01–P99',16,h-12)}
export function drawPlots(ctx,rects,state){for(const [name,r] of Object.entries(rects)){inside(ctx,r,(w,h)=>{if(name==='surface')surface(ctx,w,h,state);else if(name==='heat')heat(ctx,w,h,state);else traces(ctx,w,h,state,name==='activity')})}}
